### PR TITLE
[ci] Run workflows on both push and PR

### PR DESCRIPTION
**Pull request by jcelerier**

### CODE REVIEW

**Comment by jcelerier** [comment]
^this is what is missing so that CI runs even on PRs

**Comment by jcelerier** [comment]
@satmatthills when this is merged, rebase your other patch on top of the new main so that it runs CI in the PR too ! :)

**Review by edumeneses — APPROVED** [review]

**Comment by edumeneses** [comment]
Thanks @jcelerier and @satmatthills.

Approved and ready to merge

**Comment by jcelerier** [comment]
ty!

**Pull request merged**
